# Use the official Node.js image as the base image
FROM node:18.17-alpine AS base

# Set the working directory in the container
WORKDIR /

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./
# Install dependencies
RUN npm install && npm cache clean --force
# RUN npm ci

# Copy the rest of the application code to the working directory
COPY . .

# Build the Next.js application
RUN npm run build

ENV NEXT_PUBLIC_API_BASE_URL=http://localhost:8080

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the application
CMD ["npm", "start"]

